# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# This is the GitHub Action YAML file that deploys your Flask app to Azure Web App

name: Build and deploy Flask app to Azure Web App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Python version'
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - name: 'Install dependencies'
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: 'Create Zip File of Application'
      run: zip -r app.zip . 

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NewsletterContent' 
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 

    - name: 'Clean up'
      run: deactivate
